apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: microservices
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order-management
        image: nrsina/outbox-app-order:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8081
        env:
        - name: ORACLE_DATASOURCE_URL
          value: "jdbc:oracle:thin:@odb19c-cip-svc.oracle.svc.cluster.local:1521/ORCLPDB1"
        - name: DATASOURCE_USERNAME
          value: "c##dbzuser"
        - name: DATASOURCE_PASSWORD
          value: "dbz"
        - name: HIBERNATE_AUTO_DDL
          value: "update"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc-np
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 31081